---
# defaults file for ic_role
PGADMIN_EMAIL: "icgroup@cloudapps-cm.com"
PGADMIN_PASS: "icgroup"
PGADMIN_PORT: "8082"
DB_USER: "odoo"
DB_PASS: "odoo"
DB_NAME: "postgres"
POSTGRES_PORT: "5432"
ODOO_PORT: "8081"
IC_PORT: "80"
HOST_IP: "127.0.0.1"
IC_IMAGE_NAME: "sadofrazer/ic-webapp"
#KP_PATH: "/home/ubuntu/fsa-kp-new.pem"
