all:
  #vars:
    #ansible_ssh_private_key_file: "{{ KP_PATH }}"
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          
    prod:
      vars:
        env: production
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

      hosts:
        worker01:
          ansible_host: 172.31.82.135
          hostname: AnsibleWorker01